#!/usr/bin/env bash
# Displays "bad luck on 4 good luck on 8 and Best School else using a for loop.

counter=1

while [ $counter -le 20 ]
do
    if [ $counter -eq 4 ]; then
        echo "$counter"
        echo "bad luck from China"
    elif [ $counter -eq 9 ]; then
        echo "$counter"
        echo "bad luck from Japan"
    elif [ $counter -eq 17 ]; then
        echo "$counter"
        echo "bad luck from Italy"
    else
        echo "$counter"
    fi

    counter=$((counter + 1))
done

